### PR TITLE
Menu fixes, rewrite garage opening code, minor tweaks

### LINKED ISSUE #11: Inefficient garage opening code
https://github.com/multitheftauto/amx/blob/3330655c1c388adc4e97ec365cbb9b644a99445e/amx/client/garages.lua

It should use a colshape, as shown here in the [setGarageOpen](https://wiki.multitheftauto.com/wiki/SetGarageOpen) example.

Could generate colshape based on [garage size](https://wiki.multitheftauto.com/wiki/GetGarageSize), but it might be easier to use a [colsphere](https://wiki.multitheftauto.com/wiki/CreateColSphere) + a static radius.

### PR DESCRIPTION
**Pull request by NexiusTailer**
1. SA-MP styled menus were bugged: they didn't have critical validations; used the wrong (textdraw title) ID to add it to menu pool instead of menu ID, thus breaking any other menu related functions which later try to work with this menu; and it also used a textdraw for its title for some unknown reason, so that the title was always set with some offset related to menu box and it wasn't really attached to it.

Now it has all needed validity checks, also correctly working with nested menus (selecting an item won't produce exit event, but only selection event like SA-MP does, while exit event is only called when you really exit the menu via 'X' button or Enter key) and ofc now has its title rendered with the same means as the menu box itself, so it's a whole thing.

[Here](https://imgur.com/a/WaqQYru) is how menus look now after all the corrections.

 2. Garage opening code now uses appropriate events and checks using colsphere. This fixes [#11](https://github.com/multitheftauto/amx/issues/11)

 3. Some minor fixes for the recent changes

### CODE REVIEW

File: amx/server/natives/a_players.lua [hunk 1]
```diff
@@ -432,7 +432,7 @@ end
 function RemovePlayerAttachedObject(amx, player, index)
 	local playerID = getElemID(player)
 	local obj = g_Players[playerID].attachedObjects[index] -- Get the object stored at this slot
-	if obj ~= nil and obj ~= false then
```
Comment (colistro123) [inline amx/server/natives/a_players.lua:435]: Ahh good catch, lol 😅

**Review by colistro123 — APPROVED** [review]
LGTM, merging, thank you! 😊
